import type { Metadata } from "next";
import { Roboto} from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout/Layout";

const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});


// Tipado oficial para metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Tipado correcto para children en layouts
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${roboto.variable} antialiased`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}